[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions" # Indica a Netlify dónde están tus funciones

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200